@extends('layouts.app')

@section('title', 'Calendar & Activities')

@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <div>
        <h2><i class="bi bi-calendar-event"></i> Calendar & Activities</h2>
        <p class="text-muted mb-0">Kelola jadwal aktivitas dan follow-up</p>
    </div>
    <a href="{{ route('aktivitas.create') }}" class="btn btn-primary">
        <i class="bi bi-plus-circle"></i> Tambah Aktivitas
    </a>
</div>

<!-- Statistics Cards -->
<div class="row mb-4">
    <div class="col-md-3">
        <div class="card text-white bg-warning">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="card-title">Total Aktivitas</h6>
                        <h2 class="mb-0">{{ $totalAktivitas }}</h2>
                    </div>
                    <i class="bi bi-calendar-check" style="font-size: 3rem; opacity: 0.3;"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-info">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="card-title">Direncanakan</h6>
                        <h2 class="mb-0">{{ $aktivitasDirencanakan }}</h2>
                    </div>
                    <i class="bi bi-hourglass-split" style="font-size: 3rem; opacity: 0.3;"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-success">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="card-title">Selesai</h6>
                        <h2 class="mb-0">{{ $aktivitasSelesai }}</h2>
                    </div>
                    <i class="bi bi-check-circle" style="font-size: 3rem; opacity: 0.3;"></i>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3">
        <div class="card text-white bg-danger">
            <div class="card-body">
                <div class="d-flex justify-content-between align-items-center">
                    <div>
                        <h6 class="card-title">Hari Ini</h6>
                        <h2 class="mb-0">{{ $aktivitasHariIni }}</h2>
                    </div>
                    <i class="bi bi-calendar-day" style="font-size: 3rem; opacity: 0.3;"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Main Content Row with Calendar & List -->
<div class="row">
    <!-- Calendar Widget -->
    <div class="col-md-3 mb-4">
        <div class="card shadow-sm border-0">
            <div class="card-header bg-primary text-white">
                <div class="d-flex justify-content-between align-items-center">
                    <button class="btn btn-sm btn-light" id="prevMonth">
                        <i class="bi bi-chevron-left"></i>
                    </button>
                    <h6 class="mb-0" id="monthYear">{{ $currentMonth->isoFormat('MMMM YYYY') }}</h6>
                    <button class="btn btn-sm btn-light" id="nextMonth">
                        <i class="bi bi-chevron-right"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-3">
                <!-- Day Headers -->
                <div class="row mb-2">
                    @foreach(['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'] as $day)
                    <div class="col text-center">
                        <small class="fw-bold text-muted">{{ $day }}</small>
                    </div>
                    @endforeach
                </div>

                <!-- Calendar Grid -->
                <div id="calendarGrid" class="row g-1">
                    <!-- Generated by JavaScript -->
                </div>

                <!-- Clear Filter -->
                @if($selectedDate)
                <div class="mt-3">
                    <a href="{{ route('aktivitas.index') }}" class="btn btn-sm btn-secondary w-100">
                        <i class="bi bi-x"></i> Hapus Filter Tanggal
                    </a>
                </div>
                @endif

                <!-- Legend -->
                <div class="mt-3 pt-3 border-top">
                    <small class="d-block mb-2">
                        <span class="badge bg-primary">Hari Ini</span>
                    </small>
                    <small class="d-block mb-2">
                        <span class="badge bg-success">Ada Aktivitas</span>
                    </small>
                    <small class="d-block">
                        <span class="badge bg-light text-dark">Normal</span>
                    </small>
                </div>
            </div>
        </div>

        <!-- Upcoming Activities -->
        <div class="card shadow-sm border-0 mt-3">
            <div class="card-header bg-info text-white">
                <h6 class="mb-0"><i class="bi bi-bell"></i> Mendatang (7 hari)</h6>
            </div>
            <div class="card-body p-0">
                @php
                    $upcomingAktivitas = \App\Models\JadwalAktivitas::whereBetween('tanggal_jadwal', [
                        now(),
                        now()->addDays(7)
                    ])->where('status_aktivitas', 'direncanakan')->orderBy('tanggal_jadwal')->get();
                @endphp
                @forelse($upcomingAktivitas as $activity)
                <div class="p-2 border-bottom">
                    <small class="d-block fw-bold">{{ $activity->tanggal_jadwal->format('d M') }}</small>
                    <small class="text-muted">{{ Str::limit($activity->judul, 20) }}</small>
                </div>
                @empty
                <div class="p-3 text-center text-muted">
                    <small>Tidak ada aktivitas mendatang</small>
                </div>
                @endforelse
            </div>
        </div>
    </div>

    <!-- Activities List -->
    <div class="col-md-9">
        <!-- Filter Section -->
        <div class="card mb-4 shadow-sm border-0">
            <div class="card-body">
                <form action="{{ route('aktivitas.index') }}" method="GET" class="row g-3">
                    <div class="col-md-4">
                        <label for="jenis_aktivitas" class="form-label">Jenis Aktivitas</label>
                        <select class="form-select" id="jenis_aktivitas" name="jenis_aktivitas">
                            <option value="">Semua Jenis</option>
                            <option value="email" {{ request('jenis_aktivitas') == 'email' ? 'selected' : '' }}>📧 Email</option>
                            <option value="followup" {{ request('jenis_aktivitas') == 'followup' ? 'selected' : '' }}>📞 Follow-up</option>
                            <option value="konten" {{ request('jenis_aktivitas') == 'konten' ? 'selected' : '' }}>📝 Konten</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label for="status_aktivitas" class="form-label">Status</label>
                        <select class="form-select" id="status_aktivitas" name="status_aktivitas">
                            <option value="">Semua Status</option>
                            <option value="direncanakan" {{ request('status_aktivitas') == 'direncanakan' ? 'selected' : '' }}>⏳ Direncanakan</option>
                            <option value="selesai" {{ request('status_aktivitas') == 'selesai' ? 'selected' : '' }}>✓ Selesai</option>
                        </select>
                    </div>
                    <div class="col-md-4">
                        <label class="form-label d-block">&nbsp;</label>
                        <button type="submit" class="btn btn-primary w-100">
                            <i class="bi bi-funnel"></i> Filter
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <!-- Activities List -->
        <div class="card shadow-sm border-0">
            <div class="card-header bg-white border-bottom">
                <div class="d-flex justify-content-between align-items-center">
                    <h6 class="mb-0">
                        @if($selectedDate)
                            <i class="bi bi-calendar-check"></i> Aktivitas: {{ \Carbon\Carbon::parse($selectedDate)->isoFormat('dddd, D MMMM YYYY') }}
                        @else
                            <i class="bi bi-list-task"></i> Daftar Aktivitas
                        @endif
                    </h6>
                    <span class="badge bg-primary">{{ $aktivitas->total() }} aktivitas</span>
                </div>
            </div>
            <div class="card-body p-0">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead class="table-light">
                            <tr>
                                <th width="5%">#</th>
                                <th width="30%">Judul</th>
                                <th width="12%">Jenis</th>
                                <th width="15%">Tanggal</th>
                                <th width="15%">Pelanggan</th>
                                <th width="10%">Status</th>
                                <th width="13%">Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($aktivitas as $activity)
                            <tr class="{{ $activity->tanggal_jadwal->isToday() ? 'table-warning' : '' }}">
                                <td>{{ $loop->iteration + ($aktivitas->currentPage() - 1) * $aktivitas->perPage() }}</td>
                                <td>
                                    <strong>{{ $activity->judul }}</strong>
                                    @if($activity->tanggal_jadwal->isToday())
                                        <span class="badge bg-danger ms-1">Hari Ini!</span>
                                    @elseif($activity->tanggal_jadwal->isPast() && $activity->status_aktivitas == 'direncanakan')
                                        <span class="badge bg-warning ms-1">Terlambat</span>
                                    @endif
                                    <br>
                                    <small class="text-muted">{{ Str::limit($activity->deskripsi, 50) }}</small>
                                </td>
                                <td>
                                    <span class="badge {{ $activity->getJenisBadgeClass() }}">
                                        {{ ucfirst($activity->jenis_aktivitas) }}
                                    </span>
                                </td>
                                <td>
                                    <small>{{ $activity->tanggal_jadwal->format('d M Y') }}</small>
                                </td>
                                <td>
                                    @if($activity->pelanggan)
                                        <small>{{ Str::limit($activity->pelanggan->nama, 15) }}</small>
                                    @else
                                        <small class="text-muted">-</small>
                                    @endif
                                </td>
                                <td>
                                    <span class="badge {{ $activity->getStatusBadgeClass() }}">
                                        {{ ucfirst($activity->status_aktivitas) }}
                                    </span>
                                </td>
                                <td>
                                    <div class="btn-group btn-group-sm">
                                        <a href="{{ route('aktivitas.show', $activity) }}" class="btn btn-info" title="Lihat">
                                            <i class="bi bi-eye"></i>
                                        </a>
                                        <a href="{{ route('aktivitas.edit', $activity) }}" class="btn btn-warning" title="Edit">
                                            <i class="bi bi-pencil"></i>
                                        </a>
                                        <form action="{{ route('aktivitas.destroy', $activity) }}" method="POST" class="d-inline"
                                              onsubmit="return confirm('Hapus aktivitas ini?')">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger btn-sm" title="Hapus">
                                                <i class="bi bi-trash"></i>
                                            </button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td colspan="7" class="text-center py-5">
                                    <i class="bi bi-inbox" style="font-size: 3rem;"></i>
                                    <p class="text-muted mt-2">Tidak ada aktivitas</p>
                                </td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>

                @if($aktivitas->hasPages())
                <div class="p-3 border-top">
                    {{ $aktivitas->links() }}
                </div>
                @endif
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
document.addEventListener('DOMContentLoaded', function() {
    const calendarData = @json($calendarData);
    const selectedDate = @json($selectedDate);
    let currentDate = new Date('{{ $currentMonth->format('Y-m-01') }}');

    function renderCalendar() {
        const year = currentDate.getFullYear();
        const month = currentDate.getMonth();

        // Update header
        const monthYear = new Date(year, month);
        const monthName = monthYear.toLocaleDateString('id-ID', { month: 'long', year: 'numeric' });
        document.getElementById('monthYear').textContent = monthName.charAt(0).toUpperCase() + monthName.slice(1);

        // Generate calendar
        const firstDay = new Date(year, month, 1).getDay();
        const lastDate = new Date(year, month + 1, 0).getDate();
        const prevLastDate = new Date(year, month, 0).getDate();

        const grid = document.getElementById('calendarGrid');
        grid.innerHTML = '';

        // Previous month days
        for (let i = firstDay - 1; i >= 0; i--) {
            const date = prevLastDate - i;
            const day = document.createElement('div');
            day.className = 'col text-center p-2';
            day.innerHTML = `<small class="text-muted">${date}</small>`;
            grid.appendChild(day);
        }

        // Current month days
        for (let date = 1; date <= lastDate; date++) {
            const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(date).padStart(2, '0')}`;
            const isToday = dateStr === new Date().toISOString().split('T')[0];
            const isSelected = dateStr === selectedDate;
            const hasActivities = calendarData[dateStr];

            const day = document.createElement('div');
            day.className = 'col p-1';

            const btn = document.createElement('button');
            btn.type = 'button';
            btn.className = 'btn btn-sm w-100 position-relative';

            if (isToday) {
                btn.classList.add('btn-primary');
            } else if (isSelected) {
                btn.classList.add('btn-success');
            } else if (hasActivities) {
                btn.classList.add('btn-outline-success');
            } else {
                btn.classList.add('btn-outline-secondary');
            }

            btn.innerHTML = date;
            if (hasActivities) {
                btn.innerHTML += `<span class="position-absolute top-0 end-0 translate-middle badge rounded-pill bg-danger" style="font-size: 0.65rem;">${hasActivities.length}</span>`;
            }

            btn.addEventListener('click', (e) => {
                e.preventDefault();
                window.location.href = `?tanggal=${dateStr}`;
            });

            day.appendChild(btn);
            grid.appendChild(day);
        }

        // Next month days
        const totalCells = grid.children.length;
        const remainingCells = 42 - totalCells;
        for (let date = 1; date <= remainingCells; date++) {
            const day = document.createElement('div');
            day.className = 'col text-center p-2';
            day.innerHTML = `<small class="text-muted">${date}</small>`;
            grid.appendChild(day);
        }
    }

    document.getElementById('prevMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() - 1);
        renderCalendar();
    });

    document.getElementById('nextMonth').addEventListener('click', function() {
        currentDate.setMonth(currentDate.getMonth() + 1);
        renderCalendar();
    });

    renderCalendar();
});
</script>
@endpush
@endsection
